#!/usr/bin/env python3
"""Typeset the hero plate in the machine's engraving font.

Reads glyph outlines from the Studio checkout's glyphs.js (generated by the
firmware's cmd/textplate and drift-guarded against the pinned firmware there),
builds the hero-plate SVG, and injects it between the hero-plate markers in
index.html. --check regenerates and fails if the committed SVG drifts.

Layout mirrors the firmware's text model: monospace advance 4000 font units,
baseline at y=5000, plate 85 mm with a 3 mm margin, strokes drawn in
serpentine row order (engrave/engrave.go:1912).
"""

import json
import re
import sys
from pathlib import Path

GLYPHS_JS = Path(__file__).resolve().parent.parent.parent / "seedhammer-studio" / "glyphs.js"
INDEX = Path(__file__).resolve().parent.parent / "index.html"
BEGIN, END = "<!-- hero-plate:begin (generated by tools/gen_glyphs.py, do not edit) -->", "<!-- hero-plate:end -->"

ROWS = ["ENGRAVE", "ANYTHING."]
QUANT = 10          # font units; invisible at page scale, trims ~35% of bytes
SCALE = 2.194       # longer row (9 chars x 4000 units) fills the 79 mm inner width
ROW_Y = [26500, 45150]
DELAY0, STEP = 0.10, 0.14


def load():
    src = GLYPHS_JS.read_text()
    return json.loads(re.search(r"const SH = (\{.*\})", src, re.S).group(1).rstrip().rstrip(";"))


def quantize(d):
    return re.sub(r"-?\d+(?:\.\d+)?", lambda m: str(round(float(m.group(0)) / QUANT) * QUANT), d)


def build():
    sh = load()
    glyphs, adv = sh["glyphs"], sh["advance"]
    uniq = sorted(set("".join(ROWS)) - {" "})
    defs = "".join(f'<path id="g{ord(c)}" pathLength="1" d="{quantize(glyphs[c])}"/>' for c in uniq)

    groups, n_prev = [], 0
    for r, (text, ty) in enumerate(zip(ROWS, ROW_Y)):
        # serpentine: even rows engrave left to right, odd rows right to left
        order = range(len(text)) if r % 2 == 0 else range(len(text) - 1, -1, -1)
        delay = {i: DELAY0 + STEP * (n_prev + k) for k, i in enumerate(order)}
        n_prev += len(text)
        tx = 3000 + (79000 - len(text) * adv * SCALE) / 2
        uses = "".join(
            f'<use href="#g{ord(c)}" x="{i * adv}" style="animation-delay:{delay[i]:.2f}s"/>'
            for i, c in enumerate(text) if c != " "
        )
        groups.append(f'<g transform="translate({tx:.0f},{ty}) scale({SCALE})">{uses}</g>')

    return f'''<svg class="plate-svg" viewBox="-2500 -9000 99200 96500" role="img" aria-hidden="true">
<rect class="plate-outline" x="0" y="0" width="85000" height="85000" rx="1500"/>
<rect class="plate-margin" x="3000" y="3000" width="79000" height="79000"/>
<g class="dims" aria-hidden="true">
<line x1="0" y1="-4500" x2="85000" y2="-4500"/>
<line x1="0" y1="-5600" x2="0" y2="-3400"/>
<line x1="85000" y1="-5600" x2="85000" y2="-3400"/>
<text x="42500" y="-6300" text-anchor="middle">85.00</text>
<line x1="89500" y1="0" x2="89500" y2="85000"/>
<line x1="88400" y1="0" x2="90600" y2="0"/>
<line x1="88400" y1="85000" x2="90600" y2="85000"/>
<text x="94100" y="42500" text-anchor="middle" transform="rotate(90 94100 42500)">85.00</text>
<text x="4600" y="9300">3.00</text>
</g>
<g class="engrave-strokes">{"".join(groups)}</g>
<defs>{defs}</defs>
</svg>'''


def main():
    svg = build()
    html = INDEX.read_text()
    pre, rest = html.split(BEGIN)
    _, post = rest.split(END)
    out = f"{pre}{BEGIN}\n{svg}\n{END}{post}"
    if "--check" in sys.argv:
        if out != html:
            sys.exit("hero plate drifted from glyphs.js; run tools/gen_glyphs.py")
        print("hero plate matches glyphs.js")
        return
    INDEX.write_text(out)
    print(f"hero plate injected: {len(svg)} bytes, rows {ROWS}")


if __name__ == "__main__":
    main()
